services:
    postgres:
        container_name: mic-dining-postgres
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_USER=mic-dining
            - POSTGRES_PASSWORD=superhardpass
            - POSTGRES_DB=mic-dining
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        container_name: mic-dining-redis
        image: redis:latest
        command: ["redis-server", "--maxmemory-policy", "noeviction"]
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
volumes:
    postgres_data:
    redis_data:

networks:
    default: {}
